version: '2'
services:
    backend:
        build: ./backend
        volumes:
          - ./backend:/project/src:rw
        working_dir: /project
        ports:
          - "9060:9000"
        expose:
          - "9000"
        restart: unless-stopped
        command: node ./src/index.js
    frontend:
        image: busybox
        volumes:
          - ./frontend/dist:/project:ro
        ports:
          - "9065:80"
        links:
          - backend
        restart: unless-stopped
        command: /bin/busybox httpd -fv -h /project
