version: '2'
services:
    parser:
        build:
            context: ./parser
            dockerfile: Dockerfile-arm
        volumes:
            - ./parser:/project/src:rw
        working_dir: /project
        ports:
            - "9060:80"
        expose:
            - "80"
        restart: unless-stopped
        command: apachectl -DFOREGROUND
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile-arm
        volumes:
            - ./backend:/project/src:rw
        working_dir: /project
        ports:
            - "9065:9000"
        expose:
            - "9000"
        links:
            - parser
        restart: unless-stopped
        command: node src/index.js
