FROM armhf/debian:jessie-slim

RUN set -ex \
    && export DEBIAN_FRONTEND='noninteractive' \
    && apt-get update \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        ca-certificates

RUN set -ex \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        curl \

    && curl -sL https://deb.nodesource.com/setup_6.x | bash - \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        nodejs \
        build-essential

RUN set -ex \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        sqlite3

COPY package.json /project/
COPY content.sql /tmp/content.sql

WORKDIR /project
RUN set -ex \
    && npm install \
    && sqlite3 content.db < /tmp/content.sql \
    && rm -rf /tmp/*
